export const RESPONSES = {
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  FORBIDDEN_ACCESS: 'Forbidden Access/Operation not allowed',
  UNAUTHORIZED_ACCESS: 'Unauthorized Access',
  LOGIN_SUCCESSFUL: 'Login successful',
  USER_NOT_FOUND: 'User not found',
  USER_CREATED_SUCCESSFULLY: 'User created successfully',
  USER_LOGGED_OUT_SUCCESSFULLY: 'User logged out successfully',
  USERS_RETRIEVED_SUCCESSFULLY: 'Users retrieved successfully',
  USER_DELETED_SUCCESSFULLY: 'User deleted successfully',
  BAD_REQUEST: 'Bad Request',
  ARTISTS_RETRIEVED_SUCCESSFULLY: 'Artists retrieved successfully',
  ARTIST_RETRIEVED_SUCCESSFULLY: 'Artist retrieved successfully',
  ARTIST_NOT_FOUND: 'Artist not found',
  ARTIST_CREATED_SUCCESSFULLY: 'Artist created successfully',
  ARTIST_UPDATED_SUCCESSFULLY: 'Artist updated successfully',
  ARTIST_DELETED_SUCCESSFULLY: (name: string) => `Artist:${name} deleted successfully`,
  ALBUMS_RETRIEVED_SUCCESSFULLY: 'Albums retrieved successfully',
  ALBUM_RETRIEVED_SUCCESSFULLY: 'Album retrieved successfully',
  ALBUM_NOT_FOUND: 'Album not found',
  ALBUM_CREATED_SUCCESSFULLY: 'Album created successfully',
  ALBUM_UPDATED_SUCCESSFULLY: 'Album updated successfully',
  ALBUM_DELETED_SUCCESSFULLY: (name: string) => `Album:${name} deleted successfully`,
  TRACKS_RETRIEVED_SUCCESSFULLY: 'Tracks retrieved successfully',
  TRACK_RETRIEVED_SUCCESSFULLY: 'Track retrieved successfully',
  TRACK_NOT_FOUND: 'Track not found',
  TRACK_CREATED_SUCCESSFULLY: 'Track created successfully',
  TRACK_UPDATED_SUCCESSFULLY: 'Track updated successfully',
  TRACK_DELETED_SUCCESSFULLY: (trackName: string) => `Track:${trackName} deleted successfully`,
  FAVORITES_RETRIEVED_SUCCESSFULLY: 'Favorites retrieved successfully',
  FAVORITE_NOT_FOUND: 'Favorite not found',
  FAVORITE_ADDED_SUCCESSFULLY: 'Favorite added successfully.',
  FAVORITE_REMOVED_SUCCESSFULLY: 'Favorite removed successfully.',
  FAVORITE_ALREADY_EXISTS: 'Favorite already exists'
} as const;
